# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build jacocoTestReport dist
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jacoco-report
        path: tests/build/reports/jacoco/test/html/
    - name: Upload Jar
      uses: actions/upload-artifact@v4.3.3
      with:
        name: desktop-1.0.jar
        path: desktop/build/libs/desktop-1.0.jar
    release:
      runs-on: windows-latest
      needs: ["build"]
      if: startsWith(github.ref, 'refs/tags/')
      permissions:
        contents: write
      steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.7
          with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
            name: desktop-1.0.jar
        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            files: desktop-1.0.jar
